import { OrderTimeline, Notice, StatusChip } from "./status"; import { DeliveryTracker } from "./delivery-tracker";
import { money } from "@/lib/marketplace"; import { formatStatus, type OrderStatus } from "@/lib/domain";
import { openDispute, sellerMarkShipped, submitReview } from "@/app/phase2-actions";
type Detail={id:string;reference:string;status:OrderStatus;agreed_price:number;currency:string;seller_id:string;delivery_address?:string|null;listings:{title:string}|null;escrow_records:{status:string}[];verification_records:{status:string;rejection_reason:string|null;notes:string|null}[];deliveries:{id:string;status:string;courier_name:string|null;destination_address:string;estimated_delivery:string|null;delivery_location_updates:{id:number;latitude:number;longitude:number;recorded_at:string}[]}[];seller_reviews:{id:string}[];disputes:{id:string;status:string;reason:string}[]};
export function OrderDetail({order,role,searchParams}:{order:Detail;role:"buyer"|"seller";searchParams:{error?:string;message?:string}}){const escrow=order.escrow_records?.[0],verification=order.verification_records?.[0],delivery=order.deliveries?.[0];return <><Notice searchParams={searchParams}/><header><p className="eyebrow">{order.reference}</p><h1>{order.listings?.title}</h1><div className="actions"><StatusChip value={order.status}/>{escrow&&<StatusChip value={escrow.status}/>}</div><p className="price">{money(order.agreed_price,order.currency)}</p></header><div className="detail-grid"><section className="panel"><h2>Transaction progress</h2><OrderTimeline status={order.status}/></section><section className="panel"><h2>Current details</h2><dl className="definition-list"><dt>Order</dt><dd>{order.reference}</dd><dt>Payment</dt><dd>{escrow?formatStatus(escrow.status):"Pending"}</dd><dt>Verification</dt><dd>{verification?formatStatus(verification.status):"Not started"}</dd>{verification?.rejection_reason&&<><dt>Failure reason</dt><dd>{verification.rejection_reason}</dd></>}<dt>Delivery</dt><dd>{delivery?formatStatus(delivery.status):"Not started"}</dd></dl>
    {role==="seller"&&order.status==="awaiting_seller_shipment"&&<form action={sellerMarkShipped}><input type="hidden" name="orderId" value={order.id}/><button>Item shipped to verification center</button></form>}</section></div>
    {delivery&&<section className="panel"><div className="split"><div><p className="eyebrow">Live-style tracking</p><h2>{delivery.courier_name??"Courier assigned"}</h2></div>{delivery.estimated_delivery&&<span>ETA {new Date(delivery.estimated_delivery).toLocaleTimeString()}</span>}</div><DeliveryTracker deliveryId={delivery.id} initialPoints={delivery.delivery_location_updates??[]} destination={role==="buyer"?(order.delivery_address??"Your saved delivery address"):"Buyer destination kept private"}/></section>}
    {role==="buyer"&&order.status==="completed"&&!order.seller_reviews?.length&&<form action={submitReview} className="panel form"><h2>Review seller</h2><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="sellerId" value={order.seller_id}/><label>Rating<select name="rating" required>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label>Review<textarea name="comment" maxLength={2000}/></label><button>Publish review</button></form>}
    {!order.disputes?.length&&<form action={openDispute} className="panel form"><h2>Open a dispute</h2><input type="hidden" name="orderId" value={order.id}/><label>Reason<input name="reason" minLength={3} maxLength={120} required/></label><label>Description<textarea name="description" minLength={10} maxLength={2000} required/></label><button className="danger">Open dispute</button></form>}
    {order.disputes?.length>0&&<section className="panel"><h2>Dispute</h2>{order.disputes.map(d=><p key={d.id}><strong>{d.reason}</strong> · {formatStatus(d.status)}</p>)}</section>}</>}
